site_name: Eh Fake
theme:
  name: material
  language: pt

nav:
  - Início: index.md
  - Sobre o Projeto: sobre.md
  - Documentação:
      - Backlog: Backlog.md
      - Como baixar o RagFlow: como_baixar_ragflow.md
      - Documentação StoryMap: Documentacao_StoryMaps.md
      - Documentação Next.js: documentacao_nextjs.md
      - Documentação React: documentacao_react.md
      - Documentação Tailwind: documentacao_tailwind.md
      - Documentação Git: documentacao_git.md
      - Documentação Rag/RagFlow: documentacao_rag_ragflow.md
      - Normas de Envio: normas_de_envio.md
      - Estudo sobre Gestão: Estudo sobre Gestão.md
      - Estudo sobre Metodologias Ágeis e Scrum: Agilidade e Scrum.md
      - Estudo sobre Ciclo de Vida de Software: Estudo sobre Ciclo de Vida de Software.md
      - Documentação sobre Agentes de IA: Agentes de IA.md
      - Documento de Estratégia: Documento de Estratégia.md
      - Requisitos de Software: Requisitos de Software.md
      - Relatórios:
          - Relatório Sprint 00: relatorio_sprint_00.md
          - Relatório Sprint 01: relatorio_sprint_01.md
          - Relatório Sprint 02: relatorio_sprint_02.md
          - Relatório Sprint 03: relatorio_sprint_03.md
